// examples/sveltekit/src/lib/components/CardCta.svelte
<!--
  The escape hatch, and the one case props can't cover: `CardCta` is a nested
  presentational child, not a registered component, so the SDK has no props to
  auto-fill onto it. `getDesignValues()` reads the resolved design record of the
  nearest registered ancestor (the `Card`) off context, which lets the CTA tint
  itself with the card's own `color` without `Card` threading it down by hand.

  Reach for this only here or when you need design outside the render path (an
  effect, an imperative measurement). Registered components should style from
  props — see every other component in this directory.
-->
<script lang="ts" module>
  export interface CardCtaProps {
    label: string;
    url: string;
  }
</script>

<script lang="ts">
  import { getDesignValues } from '@contentful/experiences-svelte';

  let { label, url }: CardCtaProps = $props();

  const design = $derived(getDesignValues<{ color?: string }>());
  const style = $derived(
    [
      'margin-top: auto',
      'display: inline-block',
      'padding: 0.5rem 1rem',
      `background: ${design.color ?? '#111'}`,
      'color: #fff',
      'text-decoration: none',
      'border-radius: 0.25rem',
      'align-self: flex-start',
    ].join('; ')
  );
</script>

<a href={url} {style}>{label}</a>

// examples/angular/src/app/components/card-cta.component.ts
import { NgStyle } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input, computed, signal } from '@angular/core';
import { injectDesignValues } from '@contentful/experiences-angular';

/**
 * The escape hatch, and the one case inputs can't cover: `CardCtaComponent` is a
 * nested presentational child, not a registered component, so the SDK has no
 * inputs to auto-fill onto it. `injectDesignValues()` resolves through the
 * element-injector walk-up to the nearest registered ancestor (the card), which
 * lets the CTA tint itself with the card's own `color` without the card
 * threading it down by hand.
 *
 * Reach for this only here or when you need design outside the render path.
 * Registered components should style from their declared inputs — see every
 * other component in this directory.
 */
@Component({
  selector: 'app-card-cta',
  imports: [NgStyle],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<a [href]="urlValue()" [ngStyle]="style()">{{ labelValue() }}</a>`,
})
export class CardCtaComponent {
  protected readonly labelValue = signal('');
  protected readonly urlValue = signal<string | undefined>(undefined);

  @Input() set label(value: string | undefined) {
    this.labelValue.set(value ?? '');
  }

  @Input() set url(value: string | undefined) {
    this.urlValue.set(value);
  }

  private readonly design = injectDesignValues<{ color?: string }>();

  protected readonly style = computed(() => ({
    marginTop: 'auto',
    display: 'inline-block',
    padding: '0.5rem 1rem',
    background: this.design().color ?? '#111',
    color: '#fff',
    textDecoration: 'none',
    borderRadius: '0.25rem',
    alignSelf: 'flex-start',
  }));
}
