// examples/sveltekit/src/lib/components/HeroPlain.svelte
<!--
  Composed hero: title + optional body + CTA + hero image. All content
  properties come from a `Hero from Promotion` DataAssembly binding — this
  component just lays them out.
-->
<script lang="ts" module>
  export interface HeroPlainProps {
    title?: string;
    body?: unknown;
    ctaLabel?: string;
    ctaUrl?: string;
    image?: string;
  }
</script>

<script lang="ts">
  import { getDesignValues } from '@contentful/experiences-svelte';

  let { title, ctaLabel, ctaUrl, image }: HeroPlainProps = $props();

  const design = $derived(getDesignValues());
  const style = $derived.by(() => {
    const parts = [
      'display: grid',
      image ? 'grid-template-columns: 1fr 1fr' : 'grid-template-columns: 1fr',
      'align-items: center',
      'gap: 2rem',
      'padding: 4rem 2rem',
    ];
    if (design.backgroundColor) parts.push(`background: ${design.backgroundColor}`);
    if (design.color) parts.push(`color: ${design.color}`);
    return parts.join('; ');
  });
</script>

<section {style}>
  <div>
    {#if title}
      <h1 style="margin: 0; font-size: 2.5rem;">{title}</h1>
    {/if}
    {#if ctaLabel && ctaUrl}
      <a
        href={ctaUrl}
        style="display: inline-block; margin-top: 1.5rem; padding: 0.75rem 1.5rem; background: #111; color: #fff; text-decoration: none; border-radius: 0.25rem;"
      >
        {ctaLabel}
      </a>
    {/if}
  </div>
  {#if image}
    <img src={image} alt="" style="max-width: 100%; height: auto; border-radius: 0.5rem;" />
  {/if}
</section>

// examples/angular/src/app/components/hero-plain.component.ts
import { NgStyle } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input, computed, signal } from '@angular/core';
import { injectDesignValues } from '@contentful/experiences-angular';

interface HeroPlainDesign {
  backgroundColor?: string;
  color?: string;
}

/**
 * Composed hero: title + CTA + hero image. All content properties come from a
 * `Hero from Promotion` DataAssembly binding — this component just lays them out.
 */
@Component({
  selector: 'app-hero-plain',
  imports: [NgStyle],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [ngStyle]="style()">
      <div>
        @if (titleValue()) {
          <h1 style="margin: 0; font-size: 2.5rem;">{{ titleValue() }}</h1>
        }
        @if (ctaLabelValue() && ctaUrlValue()) {
          <a
            [href]="ctaUrlValue()"
            style="display: inline-block; margin-top: 1.5rem; padding: 0.75rem 1.5rem; background: #111; color: #fff; text-decoration: none; border-radius: 0.25rem;"
          >
            {{ ctaLabelValue() }}
          </a>
        }
      </div>
      @if (imageValue()) {
        <img
          [src]="imageValue()"
          alt=""
          style="max-width: 100%; height: auto; border-radius: 0.5rem;"
        />
      }
    </section>
  `,
})
export class HeroPlainComponent {
  protected readonly titleValue = signal<string | undefined>(undefined);
  protected readonly ctaLabelValue = signal<string | undefined>(undefined);
  protected readonly ctaUrlValue = signal<string | undefined>(undefined);
  protected readonly imageValue = signal<string | undefined>(undefined);

  @Input() set title(value: string | undefined) {
    this.titleValue.set(value);
  }

  /**
   * Declared so the renderer's input filter passes it through, even though the
   * layout ignores it — mirrors the Svelte example.
   */
  @Input() body: unknown;

  @Input() set ctaLabel(value: string | undefined) {
    this.ctaLabelValue.set(value);
  }

  @Input() set ctaUrl(value: string | undefined) {
    this.ctaUrlValue.set(value);
  }

  @Input() set image(value: string | undefined) {
    this.imageValue.set(value);
  }

  private readonly design = injectDesignValues<HeroPlainDesign>();

  protected readonly style = computed(() => {
    const design = this.design();
    return {
      display: 'grid',
      gridTemplateColumns: this.imageValue() ? '1fr 1fr' : '1fr',
      alignItems: 'center',
      gap: '2rem',
      padding: '4rem 2rem',
      ...(design.backgroundColor ? { background: design.backgroundColor } : {}),
      ...(design.color ? { color: design.color } : {}),
    };
  });
}
