// examples/sveltekit/src/lib/components/Page.svelte
<!--
  Coded Experience Template — an ordinary node in the experience. Its slots
  arrive as named `Snippet[]` props, so the payload's `content` slot lands on a
  `content` prop; there is no `children` special case.
-->
<script lang="ts" module>
  import type { Snippet } from 'svelte';

  export interface PageProps {
    title?: string;
    content?: Snippet[];
  }
</script>

<script lang="ts">
  let { title, content }: PageProps = $props();
</script>

<main style="display: flex; flex-direction: column; gap: 16px;">
  {#if title}
    <p
      style="max-width: 720px; margin: 40px auto 0; padding: 0 32px; font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; color: #6b7280;"
    >
      {title}
    </p>
  {/if}
  {#each content ?? [] as childSnippet, index (index)}
    {@render childSnippet()}
  {/each}
</main>

// examples/angular/src/app/components/page.component.ts
import { ChangeDetectionStrategy, Component, Input, signal } from '@angular/core';
import { NodesRendererComponent, type PortableRenderNode } from '@contentful/experiences-angular';

/**
 * Coded Experience Template — an ordinary node in the experience. Its slots
 * arrive as inputs named after the slot, so the payload's `content` slot lands
 * on a `content` input; there is no `children` special case.
 */
@Component({
  selector: 'app-page',
  imports: [NodesRendererComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <main style="display: flex; flex-direction: column; gap: 16px;">
      @if (titleValue()) {
        <p
          style="max-width: 720px; margin: 40px auto 0; padding: 0 32px; font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; color: #6b7280;"
        >
          {{ titleValue() }}
        </p>
      }
      <cf-nodes [nodes]="contentValue()" />
    </main>
  `,
})
export class PageComponent {
  protected readonly titleValue = signal<string | undefined>(undefined);
  protected readonly contentValue = signal<PortableRenderNode[]>([]);

  @Input() set title(value: string | undefined) {
    this.titleValue.set(value);
  }

  /** Slot input — the template's `content` slot. */
  @Input() set content(value: PortableRenderNode[] | undefined) {
    this.contentValue.set(value ?? []);
  }
}
