// packages/adapter-react/src/debug-experience.tsx
/*
 * First-party debug panel. Renders the resolved Experience plan as pretty
 * JSON so a customer can see exactly what the SDK interpreted from the payload
 * — node tree, registrations, resolved props, viewports.
 *
 * Two ways to use it:
 *  - Auto-mounted by the renderers when `debug` is on (above the tree).
 *  - Mounted manually anywhere: `<DebugExperience experience={plan} />`.
 *
 * v1 is just the JSON dump wrapped in a native <details> so it collapses
 * without any client JS (safe in server components). Room to grow into a
 * node-tree explorer, viewport indicator, and resolveData timing panel — kept
 * deliberately small for now.
 *
 * No React hooks here on purpose: it must render in both server and client
 * renderer subtrees.
 */

import type { ReactNode } from 'react';

import type { ExperienceDiagnostic, PortableRenderPlan } from '@contentful/experiences-sdk-core';

export interface DebugExperienceProps {
  /** The resolved plan to inspect (what a renderer receives as `experience`). */
  experience: PortableRenderPlan;
  /** Start expanded. Defaults to collapsed to stay out of the way. */
  defaultOpen?: boolean;
  /**
   * Resolve-time + render-time diagnostics for this render, merged by the
   * caller (`ServerExperienceRenderer` / `ClientExperienceRenderer`).
   * Defaults to `[]` for a manually-mounted `<DebugExperience>`.
   */
  errors?: ExperienceDiagnostic[];
}

export function DebugExperience({
  experience,
  defaultOpen = false,
  errors = [],
}: DebugExperienceProps): ReactNode {
  const nodeCount = experience.nodes.length;
  // Coded Experience Templates are ordinary top-level nodes, so name them from
  // the node list — a composite Experience simply has none to report.
  const templateIds = experience.nodes
    .filter((node) => node.registration.kind === 'experienceTemplate')
    .map((node) => node.registration.id);
  const summary = `Experience debug — ${nodeCount} top-level node${nodeCount === 1 ? '' : 's'}${
    templateIds.length
      ? `, experience template${templateIds.length === 1 ? '' : 's'}: ${templateIds.join(', ')}`
      : ''
  }`;

  // Auto-expand whenever there's something to see, even if the caller didn't
  // explicitly ask — a beta customer shouldn't have to know to click into a
  // collapsed panel to discover that something went wrong.
  const open = defaultOpen || errors.length > 0;

  return (
    <details
      open={open}
      data-experiences-debug
      style={{
        margin: '1rem 0',
        border: '1px solid #6b7280',
        borderRadius: '6px',
        background: '#0b1021',
        color: '#e2e8f0',
        fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
        fontSize: '0.75rem',
        overflow: 'hidden',
      }}
    >
      <summary
        style={{
          cursor: 'pointer',
          padding: '0.5rem 0.75rem',
          background: '#111827',
          userSelect: 'none',
        }}
      >
        {summary}
      </summary>
      {errors.length > 0 ? <DiagnosticList errors={errors} /> : null}
      <pre
        style={{
          margin: 0,
          padding: '0.75rem',
          overflow: 'auto',
          maxHeight: '32rem',
          whiteSpace: 'pre-wrap',
          wordBreak: 'break-word',
        }}
      >
        {safeStringify(experience)}
      </pre>
    </details>
  );
}

// Deliberately unstyled — visual treatment (grouping, color, counts) is
// AIS-407's job. This just needs to make the data visible, not console-only.
function DiagnosticList({ errors }: { errors: ExperienceDiagnostic[] }): ReactNode {
  return (
    <ul data-experiences-debug-errors>
      {errors.map((diagnostic, index) => (
        <li key={index} data-experiences-debug-error-code={diagnostic.code}>
          {diagnostic.severity} · {diagnostic.code}: {diagnostic.message}
        </li>
      ))}
    </ul>
  );
}

/**
 * JSON.stringify with a circular-reference guard. A resolved plan is plain
 * data, but a customer's `resolveData` could stash a non-serializable value on
 * `props.resolved` — degrade to a placeholder rather than throwing inside a
 * debug panel.
 */
function safeStringify(value: unknown): string {
  const seen = new WeakSet<object>();
  try {
    return JSON.stringify(
      value,
      (_key, val) => {
        if (typeof val === 'object' && val !== null) {
          if (seen.has(val)) return '[Circular]';
          seen.add(val);
        }
        if (typeof val === 'function') return `[Function ${val.name || 'anonymous'}]`;
        if (typeof val === 'undefined') return '[undefined]';
        return val;
      },
      2
    );
  } catch (err) {
    return `[DebugExperience: could not serialize plan — ${(err as Error).message}]`;
  }
}

// packages/adapter-svelte/src/DebugExperience.svelte
<!--
 * First-party debug panel. Renders the resolved Experience plan as pretty
 * JSON so a customer can see exactly what the SDK interpreted from the payload
 * — node tree, registrations, resolved props, viewports.
 *
 * Two ways to use it:
 *  - Auto-mounted by the renderers when `debug` is on (above the tree).
 *  - Mounted manually anywhere: `<DebugExperience experience={plan} />`.
 *
 * v1 is just the JSON dump wrapped in a native <details> so it collapses
 * without any extra JS. Room to grow into a node-tree explorer, viewport
 * indicator, and resolveData timing panel — kept deliberately small for now.
-->
<script lang="ts">
  import type { DebugExperienceProps } from './component-props.js';

  let { experience, defaultOpen = false, errors = [] }: DebugExperienceProps = $props();

  // Auto-expand whenever there's something to see, even if the caller didn't
  // explicitly ask — a beta customer shouldn't have to know to click into a
  // collapsed panel to discover that something went wrong.
  const open = $derived(defaultOpen || errors.length > 0);

  const nodeCount = $derived(experience.nodes.length);
  // Coded Experience Templates are ordinary top-level nodes, so name them from
  // the node list — a composite Experience simply has none to report.
  const templateIds = $derived(
    experience.nodes
      .filter((node) => node.registration.kind === 'experienceTemplate')
      .map((node) => node.registration.id)
  );
  const summary = $derived(
    `Experience debug — ${nodeCount} top-level node${nodeCount === 1 ? '' : 's'}${
      templateIds.length
        ? `, experience template${templateIds.length === 1 ? '' : 's'}: ${templateIds.join(', ')}`
        : ''
    }`
  );

  // JSON.stringify with a circular-reference guard: a customer's resolveData
  // could stash a non-serializable value on props.resolved — degrade to a
  // placeholder rather than throwing inside a debug panel.
  function safeStringify(value: unknown): string {
    const seen = new WeakSet<object>();
    try {
      return JSON.stringify(
        value,
        (_key, val) => {
          if (typeof val === 'object' && val !== null) {
            if (seen.has(val)) return '[Circular]';
            seen.add(val);
          }
          if (typeof val === 'function') return `[Function ${val.name || 'anonymous'}]`;
          if (typeof val === 'undefined') return '[undefined]';
          return val;
        },
        2
      );
    } catch (err) {
      return `[DebugExperience: could not serialize plan — ${(err as Error).message}]`;
    }
  }

  const json = $derived(safeStringify(experience));
</script>

<details
  {open}
  data-experiences-debug
  style="margin: 1rem 0; border: 1px solid #6b7280; border-radius: 6px; background: #0b1021; color: #e2e8f0; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.75rem; overflow: hidden;"
>
  <summary
    style="cursor: pointer; padding: 0.5rem 0.75rem; background: #111827; user-select: none;"
  >
    {summary}
  </summary>
  {#if errors.length > 0}
    <!-- Deliberately unstyled — visual treatment is AIS-407's job. This just
         needs to make the data visible, not console-only. -->
    <ul data-experiences-debug-errors>
      {#each errors as diagnostic, index (index)}
        <li data-experiences-debug-error-code={diagnostic.code}>
          {diagnostic.severity} · {diagnostic.code}: {diagnostic.message}
        </li>
      {/each}
    </ul>
  {/if}
  <pre
    style="margin: 0; padding: 0.75rem; overflow: auto; max-height: 32rem; white-space: pre-wrap; word-break: break-word;">{json}</pre>
</details>
