// packages/adapter-react/src/nodes-renderer.tsx
/*
 * Recursive renderer over PortableRenderNodes. Pre-renders slots into React
 * subtrees during recursion — customer components receive already-rendered
 * ReactNodes by slot name.
 *
 * Server vs client variants share this component; they differ only in how
 * the active viewport is sourced (initial seed vs reactive matchMedia).
 */

import { Fragment, type ReactNode } from 'react';

import type { PortableRenderNode, PortableTemplate } from '@contentful/experiences-core';
import { resolveDesignProperties } from '@contentful/experiences-design';

import type { MissingComponentProps } from './missing-component';
import type { ContentfulComponent, ContentfulTemplate, Config, RenderContext } from './types';

export type RenderUnknown = (props: MissingComponentProps) => ReactNode;

export interface NodesRendererProps {
  nodes: PortableRenderNode[];
  config: Config;
  experience: RenderContext;
  renderUnknown: RenderUnknown;
}

export function NodesRenderer({
  nodes,
  config,
  experience,
  renderUnknown,
}: NodesRendererProps): ReactNode {
  if (!nodes.length) return null;
  return (
    <Fragment>
      {nodes.map((node, index) => (
        <NodeRenderer
          key={node.nodeId ?? index}
          node={node}
          config={config}
          experience={experience}
          renderUnknown={renderUnknown}
        />
      ))}
    </Fragment>
  );
}

interface NodeRendererProps {
  node: PortableRenderNode;
  config: Config;
  experience: RenderContext;
  renderUnknown: RenderUnknown;
}

function NodeRenderer({ node, config, experience, renderUnknown }: NodeRendererProps): ReactNode {
  const { componentTypeId } = node.registration;
  const componentConfig = config.components[componentTypeId];
  if (!componentConfig) {
    return renderUnknown({
      componentTypeId,
      nodeId: node.nodeId,
      experience,
    });
  }

  // Pre-render slot subtrees so the parent's render fn receives ReactNodes,
  // not callables.
  const slotProps: Record<string, ReactNode> = {};
  for (const [slotName, children] of Object.entries(node.slots)) {
    slotProps[slotName] = (
      <NodesRenderer
        nodes={children}
        config={config}
        experience={experience}
        renderUnknown={renderUnknown}
      />
    );
  }

  // Resolve viewport-keyed design values into plain scalars at render time
  // (so client viewport changes don't invalidate the resolveData step).
  const resolvedDesign = resolveDesignProperties(
    node.props.design,
    experience.viewports,
    experience.activeViewportIndex
  );

  // Reserved escape-hatch prop carrying the raw Contentful-side payload
  // (componentTypeId, raw design envelopes, resolveData output, etc.).
  // Cheap to assemble — five reference fields, no clones.
  const contentful: ContentfulComponent = {
    componentTypeId,
    nodeId: node.nodeId,
    content: node.props.content,
    design: node.props.design,
    resolved: node.props.resolved,
  };

  // Merge precedence (last wins): defaults < content < design <
  // resolveData output < slots < experience < contentful.
  return componentConfig.render({
    ...componentConfig.defaults,
    ...node.props.content,
    ...resolvedDesign,
    ...node.props.resolved,
    ...slotProps,
    experience,
    contentful,
  });
}

export interface WrapWithTemplateProps {
  template: PortableTemplate | undefined;
  config: Config;
  experience: RenderContext;
  children: ReactNode;
}

/**
 * Wraps the rendered experience nodes with the page-level template when the
 * plan carries one and the customer registered a template config under that
 * id. When the template is referenced but unregistered, warns once and
 * renders children unwrapped — graceful degradation matches the
 * unknown-component fallback story.
 */
export function WrapWithTemplate({
  template,
  config,
  experience,
  children,
}: WrapWithTemplateProps): ReactNode {
  if (!template) return <Fragment>{children}</Fragment>;
  const templateConfig = config.templates?.[template.templateId];
  if (!templateConfig) {
    if (typeof console !== 'undefined') {
      console.warn(
        `[@contentful/experiences-react] No template registered for id "${template.templateId}". Rendering nodes without the template wrapper.`
      );
    }
    return <Fragment>{children}</Fragment>;
  }

  const resolvedDesign = resolveDesignProperties(
    template.props.design,
    experience.viewports,
    experience.activeViewportIndex
  );

  const contentful: ContentfulTemplate = {
    templateId: template.templateId,
    content: template.props.content,
    design: template.props.design,
    resolved: template.props.resolved,
  };

  // Merge precedence mirrors components: defaults < content < design <
  // resolveData output < children/experience/contentful.
  return templateConfig.render({
    ...templateConfig.defaults,
    ...template.props.content,
    ...resolvedDesign,
    ...template.props.resolved,
    children,
    experience,
    contentful,
  });
}

// packages/adapter-svelte/src/NodesRenderer.svelte
<!--
 * Recursive renderer over PortableRenderNodes. Customer components receive
 * a single `slot` Snippet that, when rendered with a slot name, expands to
 * that slot's pre-rendered children:
 *
 *     <script>
 *       let { text, slot } = $props();
 *     </script>
 *     <button>
 *       {text}
 *       {@render slot('children')}
 *     </button>
 *
 * Why a single `slot` snippet (parameterized by name) instead of one named
 * prop per slot like the React adapter? Svelte 5 Snippets are compile-time
 * entities — there's no way to dynamically synthesize `{children, header}`
 * snippets from runtime payload data. Passing a single dispatcher snippet
 * is the idiomatic Svelte workaround and parallels how Svelte's own
 * `<svelte:fragment slot="...">` worked in Svelte 4.
 *
 * Server vs client variants share this component; they differ only in how
 * the active viewport is sourced (initial seed vs reactive matchMedia).
-->
<script lang="ts">
  import type { PortableRenderNode } from '@contentful/experiences-core';
  import { resolveDesignProperties } from '@contentful/experiences-design';

  import NodesRenderer from './NodesRenderer.svelte';
  import type { RenderUnknown } from './component-props.js';
  import type { ContentfulComponent, Config, RenderContext } from './types.js';

  interface NodesRendererProps {
    nodes: PortableRenderNode[];
    config: Config;
    experience: RenderContext;
    renderUnknown: RenderUnknown;
  }

  let { nodes, config, experience, renderUnknown }: NodesRendererProps = $props();

  function buildProps(node: PortableRenderNode): Record<string, unknown> {
    const componentConfig = config.components[node.registration.componentTypeId];
    if (!componentConfig) return {};
    // Resolve viewport-keyed design values into plain scalars at render time
    // (so client viewport changes don't invalidate the resolveData step).
    const resolvedDesign = resolveDesignProperties(
      node.props.design,
      experience.viewports,
      experience.activeViewportIndex
    );
    // Reserved escape-hatch prop carrying the raw Contentful-side payload.
    const contentful: ContentfulComponent = {
      componentTypeId: node.registration.componentTypeId,
      nodeId: node.nodeId,
      content: node.props.content,
      design: node.props.design,
      resolved: node.props.resolved,
    };
    // Merge precedence (last wins): defaults < content < design <
    // resolveData output < experience < contentful. Slots are passed via
    // the `slot` snippet prop separately.
    return {
      ...componentConfig.defaults,
      ...node.props.content,
      ...resolvedDesign,
      ...node.props.resolved,
      experience,
      contentful,
    };
  }
</script>

{#each nodes as node, index (node.nodeId ?? index)}
  {@const componentConfig = config.components[node.registration.componentTypeId]}
  {#if componentConfig}
    {@const Cmp = componentConfig.component}
    {#snippet slot(slotName: string)}
      {@const children = node.slots[slotName] ?? []}
      <NodesRenderer nodes={children} {config} {experience} {renderUnknown} />
    {/snippet}
    <Cmp {...buildProps(node)} {slot} />
  {:else}
    {@const Unknown = renderUnknown}
    <Unknown
      componentTypeId={node.registration.componentTypeId}
      nodeId={node.nodeId}
      {experience}
    />
  {/if}
{/each}
