// packages/adapter-angular/src/server-experience-renderer.component.ts
/*
 * Server-side entry point. Port of adapter-svelte/src/ServerExperienceRenderer.svelte.
 *
 * Resolves the active viewport once, from `initialViewportId`, and never
 * reconsiders — no `matchMedia`, no listeners, nothing that touches `window`.
 * Use it wherever the render happens outside a browser: an `@angular/ssr` server
 * route, a prerender, an email or PDF pipeline.
 *
 * For a browser render that should follow viewport changes, use
 * `<cf-experience>` instead. The two are mutually exclusive: SSR cannot react to
 * a viewport the server cannot observe.
 */

import {
  ChangeDetectionStrategy,
  Component,
  Input,
  type Type,
  computed,
  inject,
  signal,
} from '@angular/core';

import { getViewportIndex } from '@contentful/experiences-design';
import type { PortableRenderPlan } from '@contentful/experiences-sdk-core';

import { DebugExperienceComponent } from './debug-experience.component.js';
import { DEFAULT_CONTEXT, EMPTY_CONFIG, FALLBACK_VIEWPORT } from './experience-defaults.js';
import { ExperienceScope } from './experience-scope.js';
import { MissingComponentComponent } from './missing-component.component.js';
import { NodesRendererDirective } from './node-renderer.directive.js';
import type { Config, RenderContext } from './types.js';

@Component({
  selector: 'cf-server-experience',
  imports: [DebugExperienceComponent, NodesRendererDirective],
  providers: [ExperienceScope],
  changeDetection: ChangeDetectionStrategy.OnPush,
  // The `<cf-server-experience>` host element itself stays a real element — it is
  // the customer's mount point, and they may well style it. Only the plumbing
  // *inside* it is anchor-only: `*cfNodes` puts the top-level nodes here as
  // siblings of a comment, so nothing the adapter owns wraps them.
  template: `
    @if (experienceValue(); as experience) {
      @if (resolvedDebug()) {
        <cf-debug-experience [experience]="experience" />
      }
      <ng-container *cfNodes="experience.nodes"></ng-container>
    }
  `,
})
export class ServerExperienceRendererComponent {
  protected readonly experienceValue = signal<PortableRenderPlan | null>(null);
  protected readonly resolvedDebug = computed(() => this.experienceValue()?.debug ?? false);
  private readonly configValue = signal<Config | null>(null);
  private readonly initialViewportIdValue = signal<string | undefined>(undefined);
  private readonly renderUnknownValue = signal<Type<unknown>>(MissingComponentComponent);

  /** A resolved render plan, or `null` while one is still being fetched. */
  @Input({ required: true }) set experience(value: PortableRenderPlan | null | undefined) {
    this.experienceValue.set(value ?? null);
  }

  @Input({ required: true }) set config(value: Config) {
    this.configValue.set(value);
  }

  /**
   * Viewport to render for, typically derived from the request's User-Agent.
   * Defaults to the viewport the plan was pre-resolved against.
   */
  @Input() set initialViewportId(value: string | undefined) {
    this.initialViewportIdValue.set(value);
  }

  /** Replaces the default missing-component box. Receives `componentId` and `nodeId`. */
  @Input() set renderUnknown(value: Type<unknown> | undefined) {
    this.renderUnknownValue.set(value ?? MissingComponentComponent);
  }

  /**
   * A `computed`, not a one-shot build: on the server it evaluates once and
   * caches, but the same class is cheap to keep correct if inputs do change
   * (a test harness rebinding, a resolved plan arriving late).
   */
  private readonly renderContext = computed<RenderContext>(() => {
    const experience = this.experienceValue();
    const initialViewportId = this.initialViewportIdValue();
    // Default to the pre-resolved viewport so first paint needs no recompute.
    const activeViewportIndex = !experience
      ? 0
      : initialViewportId === undefined
        ? experience.fallbackViewportIndex
        : getViewportIndex(experience.viewports, initialViewportId);
    return {
      ...DEFAULT_CONTEXT,
      debug: experience?.debug ?? false,
      metadata: experience?.metadata ?? DEFAULT_CONTEXT.metadata,
      viewports: experience?.viewports ?? [],
      activeViewport: experience?.viewports[activeViewportIndex] ?? FALLBACK_VIEWPORT,
      activeViewportIndex,
      fallbackViewportIndex: experience?.fallbackViewportIndex ?? 0,
    };
  });

  constructor() {
    const scope = inject(ExperienceScope);
    scope.connectExperience(() => this.renderContext());
    scope.connectConfig(() => this.configValue() ?? EMPTY_CONFIG);
    scope.connectRenderUnknown(() => this.renderUnknownValue());
  }
}

// packages/adapter-svelte/src/ServerExperienceRenderer.svelte
<!--
 * Server-safe Experience renderer. Resolves the active viewport once from
 * `initialViewportId` (typically derived from User-Agent on the request)
 * and renders without any reactive subscription. SSR-friendly.
 *
 * SSR + interactive editor mode are mutually exclusive — the message-event
 * preview client requires window listeners and lives only in the client
 * renderer. For editor mode, render the client variant on a hydrated route.
-->
<script lang="ts">
  import type { ExperienceContext, ViewportDef } from '@contentful/experiences-sdk-core';
  import { getViewportIndex } from '@contentful/experiences-design';

  import DebugExperience from './DebugExperience.svelte';
  import MissingComponent from './MissingComponent.svelte';
  import NodesRenderer from './NodesRenderer.svelte';
  import type { ServerExperienceRendererProps } from './component-props.js';
  import { setExperience } from './context.js';
  import type { RenderContext } from './types.js';

  const DEFAULT_CONTEXT: ExperienceContext = {
    debug: false,
    metadata: {},
    viewports: [],
  };

  const FALLBACK_VIEWPORT: ViewportDef = {
    id: '_',
    query: '*',
    displayName: 'Default',
    previewSize: '100%',
  };

  let {
    experience,
    config,
    initialViewportId,
    metadata,
    debug,
    renderUnknown = MissingComponent,
  }: ServerExperienceRendererProps = $props();

  // `??`, not `||`, so an explicit `debug={false}` overrides a debug-on plan.
  const resolvedDebug = $derived(debug ?? experience?.debug ?? false);

  function buildContext(): RenderContext {
    const viewports = experience?.viewports ?? [];
    // Default to the pre-resolved viewport so first paint needs no recompute.
    const idx = !experience
      ? 0
      : initialViewportId === undefined
        ? experience.fallbackViewportIndex
        : getViewportIndex(experience.viewports, initialViewportId);
    return {
      ...DEFAULT_CONTEXT,
      debug: resolvedDebug,
      metadata: {
        ...DEFAULT_CONTEXT.metadata,
        ...(experience?.metadata ?? {}),
        ...(metadata ?? {}),
      },
      viewports,
      activeViewport: experience?.viewports[idx] ?? FALLBACK_VIEWPORT,
      activeViewportIndex: idx,
      fallbackViewportIndex: experience?.fallbackViewportIndex ?? 0,
    };
  }

  const renderContext = buildContext();
  setExperience(renderContext);
</script>

{#if experience}
  {#if resolvedDebug}
    <DebugExperience {experience} />
  {/if}
  <NodesRenderer
    nodes={experience.nodes}
    {config}
    experience={renderContext}
    {renderUnknown}
  />
{/if}
