// packages/adapter-react/src/context.tsx
/*
 * React context providers + hooks that expose runtime context and the raw
 * Contentful payload to descendants of a rendered Experience. Customer
 * components receive only their declared props via the renderer; anything
 * that needs the Experience runtime context or the underlying payload calls
 * the hook explicitly at the top of its component body.
 */

'use client';

import { createContext, useContext, type ReactNode } from 'react';

import type { ContentfulComponent, ContentfulTemplate, RenderContext } from './types';

const ExperienceContext = createContext<RenderContext | null>(null);
const ContentfulComponentContext = createContext<ContentfulComponent | null>(null);
const ContentfulTemplateContext = createContext<ContentfulTemplate | null>(null);
// Plain data only (never the Config or its functions) so it crosses RSC cleanly.
const ResolvedDesignContext = createContext<Record<string, unknown> | null>(null);

// Wrapped as real client-component functions, not re-exported `Context.Provider`
// objects — the server renderer imports these across the RSC boundary and
// Next.js requires a function reference there ("Element type is invalid" otherwise).

export function ExperienceProvider({
  value,
  children,
}: {
  value: RenderContext;
  children: ReactNode;
}): ReactNode {
  return <ExperienceContext.Provider value={value}>{children}</ExperienceContext.Provider>;
}

export function ContentfulComponentProvider({
  value,
  children,
}: {
  value: ContentfulComponent;
  children: ReactNode;
}): ReactNode {
  return (
    <ContentfulComponentContext.Provider value={value}>
      {children}
    </ContentfulComponentContext.Provider>
  );
}

export function ContentfulTemplateProvider({
  value,
  children,
}: {
  value: ContentfulTemplate;
  children: ReactNode;
}): ReactNode {
  return (
    <ContentfulTemplateContext.Provider value={value}>
      {children}
    </ContentfulTemplateContext.Provider>
  );
}

export function ResolvedDesignProvider({
  value,
  children,
}: {
  value: Record<string, unknown>;
  children: ReactNode;
}): ReactNode {
  return <ResolvedDesignContext.Provider value={value}>{children}</ResolvedDesignContext.Provider>;
}

/**
 * Read the current Experience runtime context — viewports, the active
 * viewport, the `debug` flag, and free-form metadata. Throws when called
 * outside any Experience renderer subtree.
 */
export function useExperience(): RenderContext {
  const ctx = useContext(ExperienceContext);
  if (ctx === null) {
    throw new Error(
      'useExperience() must be called inside a <ServerExperienceRenderer> or <ClientExperienceRenderer> subtree.'
    );
  }
  return ctx;
}

/**
 * Read the raw Contentful payload for the nearest enclosing Experience node.
 * Returns `null` outside any rendered node (e.g. from a template's chrome
 * that wraps the nodes but isn't itself a node).
 */
export function useContentfulComponent(): ContentfulComponent | null {
  return useContext(ContentfulComponentContext);
}

/**
 * Read the raw Contentful payload for the page-level template, if one is in
 * scope. Returns `null` outside a template's render tree.
 */
export function useContentfulTemplate(): ContentfulTemplate | null {
  return useContext(ContentfulTemplateContext);
}

/**
 * Read the design values the renderer already resolved for the enclosing
 * node or template — viewport-cascaded and token-resolved, the same bag that
 * feeds the component's props. Returns `null` outside a rendered node/
 * template, which `useDesignValues` treats as "nothing to read."
 */
export function useResolvedDesign(): Record<string, unknown> | null {
  return useContext(ResolvedDesignContext);
}

// packages/adapter-angular/src/context.ts
/*
 * Accessors that expose runtime context and the raw Contentful payload to
 * descendants of a rendered Experience. Customer components receive only their
 * declared inputs from the renderer; anything that needs the Experience runtime
 * context or the underlying payload injects it here.
 *
 * Reactivity: every accessor returns a `Signal`, so reads from a template or a
 * `computed()` stay live across viewport changes. Call the signal at the point
 * of use — capturing `injectExperience()()` once loses reactivity, the same rule
 * as any other signal read.
 *
 * Like every `inject()`-based API these must be called from an injection context
 * — a field initializer or the constructor — not from a lifecycle hook or an
 * event handler.
 */

import { type Signal, inject, signal } from '@angular/core';

import { ExperienceScope } from './experience-scope.js';
import { ComponentScope, ExperienceTemplateScope } from './node-scopes.js';
import type { ContentfulComponent, ContentfulExperienceTemplate, RenderContext } from './types.js';

// Module-scope constants rather than a fresh signal per call: the value can
// never change, so readers should never be invalidated. Real signals, not
// stub functions — consumers may pass these through APIs that call `isSignal()`.
const EMPTY_COMPONENT = signal<ContentfulComponent | undefined>(undefined).asReadonly();
const EMPTY_EXPERIENCE_TEMPLATE = signal<ContentfulExperienceTemplate | undefined>(
  undefined
).asReadonly();

/**
 * Render-time experience context: viewports, active viewport, metadata, debug.
 * Throws outside a renderer subtree — reading experience context where there is
 * no experience is a programming error, not a state to branch on.
 */
export function injectExperience(): Signal<RenderContext> {
  const scope = inject(ExperienceScope, { optional: true });
  if (!scope) {
    throw new Error(
      'injectExperience() must be called inside a <cf-server-experience> or <cf-experience> subtree.'
    );
  }
  return scope.experience;
}

/**
 * Raw Contentful payload for the nearest enclosing component node. Returns a
 * signal of `undefined` outside a rendered component node.
 */
export function injectContentfulComponent(): Signal<ContentfulComponent | undefined> {
  const scope = inject(ComponentScope, { optional: true });
  return scope ? scope.node : EMPTY_COMPONENT;
}

/**
 * Raw Contentful payload for the nearest enclosing experience template node.
 * Resolves through the element-injector walk-up, so a component nested inside a
 * template still reaches the template's payload. Returns a signal of `undefined`
 * outside a rendered experience template.
 */
export function injectContentfulExperienceTemplate(): Signal<
  ContentfulExperienceTemplate | undefined
> {
  const scope = inject(ExperienceTemplateScope, { optional: true });
  return scope ? scope.template : EMPTY_EXPERIENCE_TEMPLATE;
}
