// packages/adapter-react/src/types.ts
import type { ComponentType } from 'react';

import type {
  DesignPropValue,
  RenderContext,
  ResolveContext,
  ResolveToken,
} from '@contentful/experiences-sdk-core';

/**
 * Re-exported for ergonomics: customer code authoring `resolveData` doesn't
 * have to dig into the core package for the context type.
 */
export type { ResolveContext, ResolveToken };

/**
 * The full Contentful-side payload for a single component instance, exposed
 * via `useContentfulComponent()` to any descendant of a rendered Experience
 * node. Useful for custom design-property resolution outside the SDK's
 * cascade, branching by `componentId` in a generic wrapper, keying
 * analytics on `nodeId`, or rendering a raw-payload panel in preview.
 *
 * Design properties stay in their **raw discriminated form** here (the same
 * shape `ctx.design` carries inside `resolveData`). The viewport-cascaded,
 * token-resolved values are what `useDesignValues()` returns.
 */
export interface ContentfulComponent {
  componentId: string;
  nodeId?: string;
  content: Record<string, unknown>;
  design: Record<string, DesignPropValue>;
  resolved?: Record<string, unknown>;
}

/**
 * Same shape as `ContentfulComponent`, but for an Experience Template node.
 * Exposed via `useContentfulExperienceTemplate()` inside an Experience
 * Template's component tree.
 */
export interface ContentfulExperienceTemplate {
  experienceTemplateId: string;
  nodeId?: string;
  content: Record<string, unknown>;
  design: Record<string, DesignPropValue>;
  resolved?: Record<string, unknown>;
}

/** Render-time experience context, read with `useExperience()`. Declared in core so all adapters share one shape. */
export type { RenderContext };

/**
 * Customer-supplied configuration for a single component. The `component`
 * receives the merged props (design + content + resolveData + slots); resolved
 * design values auto-fill matching props and are also readable via
 * `useDesignValues()`. Runtime context and raw payload come from
 * `useExperience()` / `useContentfulComponent()`.
 */
export interface ComponentConfig<Props extends object = Record<string, unknown>> {
  /**
   * Lowest-precedence defaults object. Merged in before content / resolveData /
   * slots. Useful for variant fallbacks the editorial layer doesn't always supply.
   */
  defaults?: Partial<Props>;
  /**
   * Optional sync-or-async hook that derives final props from the raw
   * Experience inputs. Runs once during `resolveExperience`, before render —
   * does NOT re-fire on viewport changes.
   */
  resolveData?: (ctx: ResolveContext) => Partial<Props> | Promise<Partial<Props>>;
  /**
   * The React component to render. Receives the merged props.
   */
  component: ComponentType<Props>;
}

/**
 * Registry value. Register a bare React component for the common case, or
 * the full `ComponentConfig` shape when you need defaults or a `resolveData`
 * hook.
 *
 *   button: Button,                                  // bare
 *   header: { component: Header, defaults: {...} }, // with defaults
 *   card:   defineComponent<CardProps>({ component: Card, resolveData: ... }),
 */
export type Registration<Props extends object = Record<string, unknown>> =
  ComponentType<Props> | ComponentConfig<Props>;

/**
 * Customer-supplied configuration for a coded Experience Template. Identical in
 * shape and behavior to `ComponentConfig` — an Experience Template is just a
 * node whose implementation lives in the `experienceTemplates` registry. Its
 * slots arrive as named props (a `content` slot becomes a `content` prop), so
 * there is no `children` special case.
 */
export interface ExperienceTemplateConfig<Props extends object = Record<string, unknown>> {
  /**
   * Lowest-precedence defaults object. Merged in before content / resolveData /
   * slots. Useful for variant fallbacks the editorial layer doesn't always supply.
   */
  defaults?: Partial<Props>;
  resolveData?: (ctx: ResolveContext) => Partial<Props> | Promise<Partial<Props>>;
  component: ComponentType<Props>;
}

/**
 * Registry value for Experience Templates. Same dual-shape as component
 * registrations.
 */
export type ExperienceTemplateRegistration<Props extends object = Record<string, unknown>> =
  ComponentType<Props> | ExperienceTemplateConfig<Props>;

/**
 * Identity helper — returns the config as-is, but narrows the `resolveData`
 * and `component` parameter types to your declared `Props`.
 */
export function defineComponent<Props extends object = Record<string, unknown>>(
  config: ComponentConfig<Props>
): ComponentConfig<Props> {
  return config;
}

/**
 * Identity helper — returns the Experience Template config as-is, with `Props`
 * narrowing.
 */
export function defineExperienceTemplate<Props extends object = Record<string, unknown>>(
  config: ExperienceTemplateConfig<Props>
): ExperienceTemplateConfig<Props> {
  return config;
}

/**
 * Component registry — keyed by `componentId` (last slash-segment of
 * `component.sys.urn`). Per-entry prop narrowing happens at
 * `defineComponent<Props>` or at the bare-component's own type.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- per-entry narrowing happens at the registration author's call site.
export type Components = Record<string, Registration<any>>;

/**
 * Experience Template registry — keyed by `experienceTemplateId` (last
 * slash-segment of an Experience Template node's own
 * `experienceTemplate.sys.urn`). Not read from `payload.sys`; templates are
 * ordinary nodes.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- per-entry narrowing happens at the registration author's call site.
export type ExperienceTemplates = Record<string, ExperienceTemplateRegistration<any>>;

export interface Config {
  components: Components;
  experienceTemplates?: ExperienceTemplates;
  /**
   * Resolves `DesignToken` values to runtime values before they reach a
   * component. If omitted, they pass through unchanged. See `ResolveToken`
   * in `@contentful/experiences-sdk-core` for the full contract.
   */
  resolveToken?: ResolveToken;
}

/**
 * Normalize a registry entry — bare component OR config object — into the
 * common `ComponentConfig` shape used by the renderer.
 *
 * React function components are plain functions; `React.memo` /
 * `React.forwardRef` yield objects carrying a `$$typeof` symbol. Both count
 * as bare components; a config object is discriminated by having a
 * `component` field and no `$$typeof`.
 */
export function normalizeComponentRegistration<P extends object>(
  reg: Registration<P>
): ComponentConfig<P> {
  if (typeof reg === 'object' && reg !== null && !('$$typeof' in reg) && 'component' in reg) {
    return reg as ComponentConfig<P>;
  }
  return { component: reg as ComponentType<P> };
}

export function normalizeExperienceTemplateRegistration<P extends object>(
  reg: ExperienceTemplateRegistration<P>
): ExperienceTemplateConfig<P> {
  if (typeof reg === 'object' && reg !== null && !('$$typeof' in reg) && 'component' in reg) {
    return reg as ExperienceTemplateConfig<P>;
  }
  return { component: reg as ComponentType<P> };
}

// packages/adapter-angular/src/types.ts
/*
 * Port of the Svelte adapter's types, with `Component<any>` → `Type<unknown>`.
 *
 * Input declaration convention for this package: every component in `src/`
 * declares its inputs with the `@Input()` decorator plus a setter that writes
 * into a private signal, never with the signal-based `input()`.
 *
 * Signal inputs are AOT-only. Angular's JIT compiler builds a component def's
 * `inputs` map from decorator metadata and never scans class-field initializers,
 * so under JIT an `input()` field is invisible to `reflectComponentType()` and
 * `ComponentRef.setInput()` rejects it (NG0303). This suite runs on JIT — see
 * the note in vitest.config.ts — so the decorator form is load-bearing here.
 *
 * This constraint applies only to the adapter's own components and its test
 * fixtures. Customer-registered components are compiled by the customer's own
 * AOT build and may declare signal inputs freely: the renderer discovers them
 * with `reflectComponentType()` and assigns them with `setInput()`, both of
 * which are runtime APIs that read whatever the component def already carries.
 */

import type { Type } from '@angular/core';

import type {
  DesignPropValue,
  PortableRenderNode,
  RenderContext,
  ResolveContext,
  ResolveToken,
} from '@contentful/experiences-sdk-core';

export type { ResolveContext, ResolveToken };

/**
 * The full Contentful-side payload for a single component instance, exposed
 * via `injectContentfulComponent()` to any descendant of a rendered Experience
 * node. Useful for custom design-property resolution outside the SDK's
 * cascade, branching by `componentId` in a generic wrapper, keying
 * analytics on `nodeId`, rendering a raw-payload panel in preview, or
 * re-rendering a slot's nodes yourself through the exported `*cfNodes`.
 *
 * Design properties stay in their **raw discriminated form** here (the same
 * shape `ctx.design` carries inside `resolveData`). The viewport-cascaded,
 * token-resolved values are what `injectDesignValues()` returns.
 */
export interface ContentfulComponent {
  componentId: string;
  nodeId?: string;
  content: Record<string, unknown>;
  design: Record<string, DesignPropValue>;
  resolved?: Record<string, unknown>;
  /**
   * Raw per-slot node arrays from the payload. Every slot is also passed as a
   * same-named `PortableRenderNode[]` input (`children` is not special); these
   * raw nodes are the same arrays, kept here for callers that reach a slot
   * through the context rather than through a declared input.
   */
  slots: Record<string, unknown>;
}

/**
 * Same shape as `ContentfulComponent`, but for an Experience Template node.
 * Exposed via `injectContentfulExperienceTemplate()` inside an Experience
 * Template's component tree.
 */
export interface ContentfulExperienceTemplate {
  experienceTemplateId: string;
  nodeId?: string;
  content: Record<string, unknown>;
  design: Record<string, DesignPropValue>;
  resolved?: Record<string, unknown>;
}

/** Render-time experience context, read with `injectExperience()`. Declared in core so all adapters share one shape. */
export type { RenderContext };

/**
 * Customer-supplied configuration for a single component type. The `component`
 * receives the merged props (design + content + resolveData + one
 * `PortableRenderNode[]` input per slot); resolved design values auto-fill
 * matching inputs and are also readable via `injectDesignValues()`. Runtime
 * context and raw payload come from `injectExperience()` /
 * `injectContentfulComponent()`.
 *
 * Only keys the component declares as inputs are assigned — see
 * `Registration` and the README's parity table.
 */
export interface ComponentConfig<Props extends object = Record<string, unknown>> {
  /**
   * Lowest-precedence defaults object. Merged in before content / resolveData /
   * slots. Useful for variant fallbacks the editorial layer doesn't always supply.
   */
  defaults?: Partial<Props>;
  resolveData?: (ctx: ResolveContext) => Partial<Props> | Promise<Partial<Props>>;
  component: Type<unknown>;
}

/**
 * Registry value. Register a bare Angular component class for the common case,
 * or the full `ComponentConfig` shape when you need defaults or a `resolveData`
 * hook.
 *
 *   button: ButtonComponent,                                 // bare
 *   header: { component: HeaderComponent, defaults: {...} },  // with defaults
 *   card:   defineComponent<CardProps>({ component: CardComponent, resolveData: ... }),
 */
export type Registration<Props extends object = Record<string, unknown>> =
  Type<unknown> | ComponentConfig<Props>;

/**
 * Customer-supplied configuration for a coded Experience Template. Identical in
 * shape and behavior to `ComponentConfig` — an Experience Template is just a
 * node whose implementation lives in the `experienceTemplates` registry. Its
 * slots arrive as named `PortableRenderNode[]` inputs (a `content` slot becomes
 * a `content` input), so there is no `children` special case.
 */
export interface ExperienceTemplateConfig<Props extends object = Record<string, unknown>> {
  /**
   * Lowest-precedence defaults object. Merged in before content / resolveData /
   * slots. Useful for variant fallbacks the editorial layer doesn't always supply.
   */
  defaults?: Partial<Props>;
  resolveData?: (ctx: ResolveContext) => Partial<Props> | Promise<Partial<Props>>;
  component: Type<unknown>;
}

export type ExperienceTemplateRegistration<Props extends object = Record<string, unknown>> =
  Type<unknown> | ExperienceTemplateConfig<Props>;

export function defineExperienceTemplate<Props extends object = Record<string, unknown>>(
  config: ExperienceTemplateConfig<Props>
): ExperienceTemplateConfig<Props> {
  return config;
}

export function defineComponent<Props extends object = Record<string, unknown>>(
  config: ComponentConfig<Props>
): ComponentConfig<Props> {
  return config;
}

/**
 * Component registry — keyed by `componentId` (last slash-segment of
 * `component.sys.urn`).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- registry values are heterogeneous; each entry's Props is its own.
export type Components = Record<string, Registration<any>>;

/**
 * Experience Template registry — keyed by `experienceTemplateId` (last
 * slash-segment of an Experience Template node's own
 * `experienceTemplate.sys.urn`). Not read from `payload.sys`; templates are
 * ordinary nodes.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type ExperienceTemplates = Record<string, ExperienceTemplateRegistration<any>>;

export interface Config {
  components: Components;
  experienceTemplates?: ExperienceTemplates;
  /**
   * Resolves `DesignToken` values to runtime values before they reach a
   * component. If omitted, they pass through unchanged. See `ResolveToken`
   * in `@contentful/experiences-sdk-core` for the full contract.
   */
  resolveToken?: ResolveToken;
}

/**
 * Normalize a registry entry — bare Angular component class OR config object —
 * into the common `ComponentConfig` shape used by the renderer. Component
 * classes are functions; config objects are plain objects with a `component`
 * field, so `typeof` is enough to discriminate.
 */
export function normalizeComponentRegistration<P extends object>(
  reg: Registration<P>
): ComponentConfig<P> {
  if (typeof reg === 'function') {
    return { component: reg as Type<unknown> } as ComponentConfig<P>;
  }
  return reg;
}

export function normalizeExperienceTemplateRegistration<P extends object>(
  reg: ExperienceTemplateRegistration<P>
): ExperienceTemplateConfig<P> {
  if (typeof reg === 'function') {
    return { component: reg as Type<unknown> } as ExperienceTemplateConfig<P>;
  }
  return reg;
}

/**
 * Renders the unregistered-component placeholder. Receives `componentId` and
 * `nodeId` inputs; anything it does not declare is dropped, same as any other
 * rendered component.
 */
export type RenderUnknown = Type<unknown>;

/**
 * Renders the fallback for a registered component that threw. Receives
 * `componentId`, `nodeId`, and `message` inputs; anything it does not
 * declare is dropped, same as any other rendered component.
 */
export type RenderError = Type<unknown>;

/** Convenience alias — the slot input shape customer components declare. */
export type SlotNodes = PortableRenderNode[];
