// test-apps/nextjs/components/Section.tsx
'use client';

import type { CSSProperties, ReactNode } from 'react';

type Align = 'start' | 'center' | 'end' | 'stretch';

const ALIGN: Record<Align, CSSProperties['alignItems']> = {
  start: 'flex-start',
  center: 'center',
  end: 'flex-end',
  stretch: 'stretch',
};

// Flex/grid layout primitive. Design keys arrive as auto-filled props, already
// server-resolved (cascade + token resolution), so token-valued keys are CSS.
export interface SectionProps {
  // Slot children arrive as an array of pre-rendered nodes — drop it straight
  // into JSX to render them all (React renders arrays), or map/filter/wrap the
  // children individually.
  children?: ReactNode[];
  // Design props:
  direction?: 'row' | 'column';
  reverse?: boolean;
  ratio?: string;
  itemAlign?: Align;
  gap?: string;
  verticalSpacing?: string;
  horizontalSpacing?: string;
  backgroundColor?: string;
  color?: string;
  radius?: string;
}

export function Section(props: SectionProps) {
  console.log('[Section] resolved props →', props);

  const {
    children,
    direction = 'column',
    reverse = false,
    ratio,
    itemAlign = 'stretch',
    gap,
    verticalSpacing,
    horizontalSpacing,
    backgroundColor,
    color,
    radius,
  } = props;

  const flexDirection =
    `${direction}${reverse ? '-reverse' : ''}` as CSSProperties['flexDirection'];

  const style: CSSProperties = {
    display: 'flex',
    flexDirection,
    alignItems: ALIGN[itemAlign],
    gap: gap ?? undefined,
    paddingBlock: verticalSpacing ?? undefined,
    paddingInline: horizontalSpacing ?? undefined,
    backgroundColor: backgroundColor ?? undefined,
    color: color ?? undefined,
    borderRadius: radius ?? undefined,
  };

  // A colon ratio ("1:2:1") lays children out in grid tracks; else flex.
  if (ratio && ratio.includes(':')) {
    const tracks = ratio
      .split(':')
      .map((n) => `${Number(n) || 1}fr`)
      .join(' ');
    style.display = 'grid';
    style.gridTemplateColumns = direction === 'column' ? undefined : tracks;
    style.gridTemplateRows = direction === 'column' ? tracks : undefined;
    delete style.flexDirection;
    delete style.alignItems;
  }

  return <div style={style}>{children}</div>;
}

// examples/sveltekit/src/lib/components/Section.svelte
<script lang="ts" module>
  import type { Snippet } from 'svelte';

  export interface SectionProps {
    // Slot children arrive as an array of Snippets — one per child node — so a
    // component can render them all or map/filter/wrap them individually.
    children?: Snippet[];
    // Design properties, auto-filled as props. Declare the ones you consume by
    // name; `direction` and `columns` are semantic keys this component maps onto
    // flex/grid itself, the rest are CSS-shaped.
    direction?: 'row' | 'column';
    columns?: string;
    itemAlign?: string;
    gap?: string;
    verticalSpacing?: string;
    horizontalSpacing?: string;
    backgroundColor?: string;
    color?: string;
  }
</script>

<script lang="ts">
  let {
    children,
    direction = 'column',
    columns,
    gap,
    verticalSpacing,
    horizontalSpacing,
    backgroundColor,
    color,
  }: SectionProps = $props();

  const style = $derived.by(() => {
    const parts: string[] = [];
    if (columns && columns !== 'auto') {
      parts.push('display: grid');
      const tracks = `repeat(${columns}, minmax(0, 1fr))`;
      parts.push(
        direction === 'column' ? `grid-template-rows: ${tracks}` : `grid-template-columns: ${tracks}`
      );
    } else {
      parts.push('display: flex');
      parts.push(`flex-direction: ${direction}`);
    }
    if (gap) parts.push(`gap: ${gap}`);
    if (verticalSpacing) parts.push(`padding-block: ${verticalSpacing}`);
    if (horizontalSpacing) parts.push(`padding-inline: ${horizontalSpacing}`);
    if (backgroundColor) parts.push(`background: ${backgroundColor}`);
    if (color) parts.push(`color: ${color}`);
    return parts.join('; ');
  });
</script>

<div {style}>
  {#each children ?? [] as child}
    {@render child()}
  {/each}
</div>
