// examples/nextjs/components/Text.tsx
'use client';

import type { CSSProperties, ReactNode } from 'react';

export interface TextProps {
  text?: string | null;
  children?: ReactNode;
  // Design properties, auto-filled as props.
  align?: CSSProperties['textAlign'];
  fontSize?: string;
}

export function Text({ text, children, align, fontSize = '16px' }: TextProps) {
  if (!text && !children) return null;

  const style: CSSProperties = {
    margin: 0,
    color: '#4b5563',
    lineHeight: 1.5,
    fontSize,
    textAlign: align,
  };

  return (
    <p style={style}>
      {text}
      {children}
    </p>
  );
}

// examples/sveltekit/src/lib/components/Text.svelte
<script lang="ts" module>
  export interface TextProps {
    text?: string;
    // Design properties, auto-filled as props.
    align?: string;
    fontSize?: string;
  }
</script>

<script lang="ts">
  let { text, align, fontSize = '16px' }: TextProps = $props();

  const style = $derived(
    [
      `font-size: ${fontSize}`,
      'line-height: 1.5',
      'color: #4b5563',
      'margin: 0',
      align && `text-align: ${align}`,
    ]
      .filter(Boolean)
      .join('; ')
  );
</script>

<p {style}>{text ?? ''}</p>
