// test-apps/sveltekit/src/lib/components/Button.svelte
<!--
  Design-system button. Knows nothing about Contentful — it's a plain
  Svelte component the experience-config wires up.
-->
<script lang="ts" module>
  import type { Snippet } from 'svelte';

  export type ButtonType = 'primary' | 'secondary';

  export interface ButtonProps {
    text?: string;
    url?: string;
    type?: ButtonType;
    children?: Snippet;
  }

  const PALETTE: Record<ButtonType, { background: string; color: string; border: string }> = {
    primary: { background: '#4f39f6', color: '#ffffff', border: 'none' },
    secondary: { background: '#ffffff', color: '#1f2937', border: '1px solid #d1d5db' },
  };
</script>

<script lang="ts">
  let { text = 'Button', url, type = 'primary', children }: ButtonProps = $props();
  const palette = $derived(PALETTE[type]);
  const style = $derived(
    [
      'display: inline-flex',
      'align-items: center',
      'gap: 6px',
      'padding: 12px 18px',
      'border-radius: 8px',
      `background: ${palette.background}`,
      `color: ${palette.color}`,
      'font-weight: 500',
      `border: ${palette.border}`,
      'text-decoration: none',
      'cursor: pointer',
    ].join('; ')
  );
</script>

{#if url}
  <a href={url} {style} rel="noopener noreferrer">
    {text}
    {#if children}{@render children()}{/if}
  </a>
{:else}
  <button type="button" {style}>
    {text}
    {#if children}{@render children()}{/if}
  </button>
{/if}

// examples/nextjs/components/Button.tsx
import type { CSSProperties, ReactNode } from 'react';

export type ButtonType = 'primary' | 'secondary';

export interface ButtonProps {
  text?: string;
  url?: string;
  type?: ButtonType;
  children?: ReactNode;
}

const PALETTE: Record<ButtonType, CSSProperties> = {
  primary: { background: '#4f39f6', color: '#ffffff' },
  secondary: { background: '#ffffff', color: '#1f2937', border: '1px solid #d1d5db' },
};

export function Button({ text, url, type = 'primary', children }: ButtonProps) {
  const palette = PALETTE[type];
  const style: CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '12px 18px',
    borderRadius: 8,
    background: palette.background,
    color: palette.color,
    fontWeight: 500,
    border: palette.border ?? 'none',
    textDecoration: 'none',
    cursor: 'pointer',
  };

  const content = (
    <>
      {text ?? 'Button'}
      {children}
    </>
  );
  if (url) {
    return (
      <a href={url} style={style} rel="noopener noreferrer">
        {content}
      </a>
    );
  }
  return (
    <button type="button" style={style}>
      {content}
    </button>
  );
}
