// examples/sveltekit/src/lib/components/Page.svelte
<!--
  Page-level template. Receives the rendered experience nodes via the
  `children` Snippet and wraps them with the page chrome.
-->
<script lang="ts" module>
  import type { Snippet } from 'svelte';

  export interface PageProps {
    title?: string;
    children: Snippet;
  }
</script>

<script lang="ts">
  let { title, children }: PageProps = $props();
</script>

<main
  style="max-width: 720px; margin: 40px auto; padding: 32px; background: #ffffff; border-radius: 16px; border: 1px solid #e5e7eb; display: flex; flex-direction: column; gap: 16px;"
>
  {#if title}
    <p
      style="font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; color: #6b7280; margin: 0;"
    >
      {title}
    </p>
  {/if}
  {@render children()}
</main>

// examples/nextjs/components/Page.tsx
import type { CSSProperties, ReactNode } from 'react';

export interface PageProps {
  title?: string;
  children?: ReactNode;
}

export function Page({ title, children }: PageProps) {
  const wrapper: CSSProperties = {
    maxWidth: 720,
    margin: '40px auto',
    padding: 32,
    background: '#ffffff',
    borderRadius: 16,
    border: '1px solid #e5e7eb',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  };
  const titleStyle: CSSProperties = {
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    color: '#6b7280',
    margin: 0,
  };
  return (
    <main style={wrapper}>
      {title ? <p style={titleStyle}>{title}</p> : null}
      {children}
    </main>
  );
}
