// examples/angular/src/app/components/text.component.ts
import { NgStyle } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input, computed, signal } from '@angular/core';
import { injectDesignValues, toCss } from '@contentful/experiences-angular';

interface TextDesign {
  align?: string;
}

@Component({
  selector: 'app-text',
  imports: [NgStyle],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<p [ngStyle]="style()">{{ textValue() }}</p>`,
})
export class TextComponent {
  protected readonly textValue = signal('');

  @Input() set text(value: string | undefined) {
    this.textValue.set(value ?? '');
  }

  private readonly design = injectDesignValues<TextDesign>();

  protected readonly style = computed(() => {
    const design = this.design();
    return {
      fontSize: '16px',
      lineHeight: '1.5',
      color: '#4b5563',
      margin: '0',
      ...(design.align ? { textAlign: design.align } : {}),
      ...toCss(design),
    };
  });
}

// examples/nextjs/components/Text.tsx
'use client';

import type { CSSProperties, ReactNode } from 'react';

import { useDesignValues } from '@contentful/experiences-react';

export interface TextProps {
  text?: string | null;
  children?: ReactNode;
}

export function Text({ text, children }: TextProps) {
  const design = useDesignValues();
  if (!text && !children) return null;

  const style: CSSProperties = {
    margin: 0,
    color: '#4b5563',
    lineHeight: 1.5,
    fontSize: (design.fontSize as string) ?? '16px',
    textAlign: (design.align as CSSProperties['textAlign']) ?? undefined,
  };

  return (
    <p style={style}>
      {text}
      {children}
    </p>
  );
}
