// examples/sveltekit/src/lib/components/Page.svelte
<!--
  Page-level Experience Template. Receives the rendered experience nodes via the
  `children` Snippet and wraps them with the page chrome.
-->
<script lang="ts" module>
  import type { Snippet } from 'svelte';

  export interface PageProps {
    title?: string;
    children: Snippet;
  }
</script>

<script lang="ts">
  let { title, children }: PageProps = $props();
</script>

<main style="display: flex; flex-direction: column; gap: 16px;">
  {#if title}
    <p
      style="max-width: 720px; margin: 40px auto 0; padding: 0 32px; font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; color: #6b7280;"
    >
      {title}
    </p>
  {/if}
  {@render children()}
</main>

// test-apps/nextjs/components/Page.tsx
import type { CSSProperties, ReactNode } from 'react';

export interface PageProps {
  title?: string;
  children?: ReactNode;
}

/** Page-level Experience Template: wraps all top-level nodes in the outer page chrome. */
export function Page({ children }: PageProps) {
  const wrapper: CSSProperties = {
    maxWidth: 1024,
    margin: '0 auto',
    padding: '48px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: 48,
  };
  return <main style={wrapper}>{children}</main>;
}
