// examples/sveltekit/src/lib/components/RichText.svelte
<script lang="ts" module>
  // Minimal rich-text renderer — matches the Next.js example's coverage:
  // paragraphs + bold/italic marks. The document shape follows Contentful's
  // rich-text-types (nodeType: 'document' | 'paragraph' | 'text', marks[]).

  type Mark = { type: 'bold' | 'italic' | 'underline' | 'code' };
  type TextNode = { nodeType: 'text'; value: string; marks?: Mark[] };
  type Paragraph = { nodeType: 'paragraph'; content: TextNode[] };
  type RichDoc = { nodeType: 'document'; content: Paragraph[] };

  export interface RichTextProps {
    document?: unknown;
    // Design properties, auto-filled as props.
    align?: string;
    fontSize?: string;
  }

  function extractDoc(input: unknown): RichDoc | null {
    if (!input || typeof input !== 'object') return null;
    const outer = input as { document?: unknown; nodeType?: string };
    if (outer.nodeType === 'document') return outer as RichDoc;
    if (outer.document && typeof outer.document === 'object') {
      return extractDoc(outer.document);
    }
    return null;
  }
</script>

<script lang="ts">
  let { document, align, fontSize }: RichTextProps = $props();
  const doc = $derived(extractDoc(document));

  const style = $derived(
    [align && `text-align: ${align}`, fontSize && `font-size: ${fontSize}`]
      .filter(Boolean)
      .join('; ')
  );
</script>

{#if doc}
  <div {style}>
    {#each doc.content as p}
      <p style="margin: 0 0 0.75em; line-height: 1.5;">
        {#each p.content as span}
          {#if span.marks?.some((m) => m.type === 'bold')}<strong>{span.value}</strong>
          {:else if span.marks?.some((m) => m.type === 'italic')}<em>{span.value}</em>
          {:else}{span.value}{/if}
        {/each}
      </p>
    {/each}
  </div>
{/if}

// test-apps/nextjs/components/RichText.tsx
'use client';

import { Fragment, type CSSProperties, type ReactNode } from 'react';

// Minimal rich-text renderer (paragraphs + bold/italic) so the app stays
// dependency-free; a real app would use @contentful/rich-text-react-renderer.

interface Mark {
  type: string;
}
interface RichTextNode {
  nodeType: string;
  value?: string;
  marks?: Mark[];
  content?: RichTextNode[];
}

// XDA wraps the document as `{ __typename, document }`; inner can be null.
export interface RichTextProps {
  document?: {
    document?: RichTextNode | null;
  } | null;
  // Design props (auto-filled, server-resolved):
  fontSize?: string;
  align?: CSSProperties['textAlign'];
}

function renderNode(node: RichTextNode, key: number): ReactNode {
  switch (node.nodeType) {
    case 'document':
      return <Fragment key={key}>{(node.content ?? []).map(renderNode)}</Fragment>;
    case 'paragraph':
      return (
        <p key={key} style={{ margin: '0 0 12px' }}>
          {(node.content ?? []).map(renderNode)}
        </p>
      );
    case 'text': {
      let el: ReactNode = node.value ?? '';
      for (const mark of node.marks ?? []) {
        if (mark.type === 'bold') el = <strong>{el}</strong>;
        if (mark.type === 'italic') el = <em>{el}</em>;
      }
      return <Fragment key={key}>{el}</Fragment>;
    }
    default:
      return <Fragment key={key}>{(node.content ?? []).map(renderNode)}</Fragment>;
  }
}

export function RichText(props: RichTextProps) {
  console.log('[RichText] resolved props →', props);

  const { document, fontSize, align } = props;
  const doc = document?.document;
  if (!doc) return null;

  const style: CSSProperties = {
    color: '#4b5563',
    lineHeight: 1.6,
    fontSize: fontSize ?? undefined,
    textAlign: align ?? undefined,
  };

  return <div style={style}>{renderNode(doc, 0)}</div>;
}
